### ISSUE TITLE
EFCore Settings are applied to ignored properties

### ISSUE THREAD

**Issue by PSMGoossens** [kyleherzog/ExtendableEnums#71]
The extension method _ApplyExtendableEnumConversions_ is applying the operations also to properties that are excluded from the model, resulting in possible runtime errors when applying the configuration.

The extension method _ApplyExtendableEnumConversions_ should not apply the configuration when:

- The property is decorated with NotMappedAttribute
- The property is "Ignored" by ModelBuilder before this execution

I will create a PR that will take this issues into account.

**Comment by kyleherzog** [comment]
Thanks for the feedback. I just tried to address this with version 9.1.  It is available now as a beta NuGet package.  Can you confirm that this fixes the issue?
