### ISSUE TITLE
.NET 9 problem with recursive type definition

### ISSUE THREAD

**Issue by nitinbabbar-microsea** [kyleherzog/ExtendableEnums#72]
Hi Kyle
We enjoy using your package. Currently we're updating our software from .NET 8 to .NET 9. Unfortunately we're having a blocking issue in runtime with ExtendedEnumBase<´2> class.

It's easy to reproduce:
`
@code {
    public abstract class ExtendableEnumBase<TEnumeration, TValue>
        where TEnumeration : ExtendableEnumBase<TEnumeration, TValue>
    {
        private static readonly Lazy<TEnumeration[]> enumerations = new Lazy<TEnumeration[]>();
    }

    public class FooType : ExtendableEnumBase<FooType, int>
    {
    }
}`

If you instantiate FooType in a Blazor Wasm App then you get an error in .NET 9.

This is stack trace of the error
Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Could not set up parent class, due to: Recursive type definition detected .ExtendableEnumBase`2 assembly:Net9DependencyIssue.dll type:ExtendableEnumBase`2 member:(null)
**System.TypeLoadException: Could not set up parent class, due to: Recursive type definition detected .ExtendableEnumBase`2** assembly:Net9DependencyIssue.dll type:ExtendableEnumBase`2 member:(null)
   at Microsoft.AspNetCore.Components.EventCallbackWorkItem.InvokeAsync[Object](MulticastDelegate delegate, Object arg)
   at Microsoft.AspNetCore.Components.EventCallbackWorkItem.InvokeAsync(Object arg)
   at Microsoft.AspNetCore.Components.ComponentBase.Microsoft.AspNetCore.Components.IHandleEvent.HandleEventAsync(EventCallbackWorkItem callback, Object arg)
   at Microsoft.AspNetCore.Components.EventCallback.InvokeAsync(Object arg)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.DispatchEventAsync(UInt64 eventHandlerId, EventFieldInfo fieldInfo, EventArgs eventArgs, Boolean waitForQuiescence)

This type of error is reported to dotnet team but in connection with another package. https://github.com/dotnet/runtime/issues/109931
Can you help us out here?
Thank you and best regards 👍 
Nitin

**Comment by kyleherzog** [comment]
Thanks for the feedback. I was able to reproduce the issue.  I just released version 9.0.6 to address the issue.

**Comment by cssack** [comment]
Your commitment is amazing! Thank you

**Comment by nitinbabbar-microsea** [comment]
Dear Kyle
Thank you very much for resolving this issue. Our Team really appreciates your effort.
Have a good and successful day ahead! 👍 
Nitin
